controller_manager:
  ros_parameters:
    update_rate: 10

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - base_1_joint
        - 1_2_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
      open_loop_control: true
      allow_integration_in_goal_trajectories: true

    arm1_controller:
      type: forward_command_controller/ForwardCommandController
      joints:
        - 2_3_joint
      interface_name: position

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
